### ISSUE TITLE
Usage note

### ISSUE THREAD

**Issue by vhscom** [jhubbardsf/vite-plugin-svelte-console-remover#1]
I'm sure this wasn't easy to create. And I applaud you for doing so. But I think it might be worth noting in the README the same thing can be accomplished along with dropping debuggers with a [few lines of Vite config](https://github.com/vitejs/vite/discussions/7920).

SvelteKit users:

```js
kit: {
  adapter: adapter(),
  vite: {
    esbuild: { drop: ['console', 'debugger'] }
  }
}
```

I opened this issue in hopes to get this documented and prevent Vite plug-in sprawl in SvelteKit. I hope you will consider documenting this for the benefit of your users and those who are still learning to help them keep their apps as simple as possible.

**Comment by jhubbardsf** [comment]
Good point!

**Comment by jhubbardsf** [comment]
Updated the readme and linked to the esbuild drop config.
